### ISSUE TITLE
REPORTE PRACTICA FINAL

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/practica-final-de-hilos-team-check#2]
[PRACTICA FINAL HILOS_EQUIPO.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-team-check/files/6498308/PRACTICA.FINAL.HILOS_EQUIPO.pdf)

**Comment by Anthony4523** [comment]
Calificación: 20
Cumple con todos los requisitos. Solamente hay que estructurarlo un poco más.

**Comment by josealfredo79** [comment]
Revisado y bien hecho.
